@startuml
class Book {
    - title: String
    - author: String
    - yearOfPublication: int
    - relevantData: String
}
class User {
    - booksRegistered: set[Book]
    + registerBook(book: Book)
}
User "1" --> "*" Book
@enduml