@startuml
   class Book {
       - title: String
       - author: String
       - publicationYear: int
       - otherRelevantData: String
   }

   class User {
       - username: String
       - password: String
       - registeredBooks: set[Book]
   }
   @enduml