@startuml
   class Player {
       - dice1: Die
       - dice2: Die
       - currentTurnResult: Integer
       + rollDice(): void
       + getCurrentTurnResult(): Integer
   }

   class Die {
       - value: Integer
       + setValue(value: Integer): void
       + getValue(): Integer
   }
   @enduml