@startuml
class User {
    - username: String
    - email: String
    + registerBook(book: Book): boolean
    + accessBookData(bookId: String): Book
}

class Book {
    - title: String
    - author: String
    - yearOfPublication: int
    - isbn: String
    - genre: String
    + getBasicInformation(): String
    + updateInformation(): boolean
}

User --> Book : manages
@enduml