@startuml
class User {
    - name: String
    - userType: String
    + getName(): String
    + getUserType(): String
    + updateInformation(): void
}

class Student {
    + getStudentInfo(): String
}

class Teacher {
    + getTeacherInfo(): String
}

Student --|> User
Teacher --|> User
@enduml