@startuml
class SystemUser {
  + register(): boolean
  + viewProfile()
  + manageProfileInformation()
  + accessSystemFunctionalities()
}

class Profile {
  - basicInformation: String
}

SystemUser "1" *-- "1" Profile
@enduml