@startuml
class User Ellipsis {
  - name: String
  - userType: String
  + getName(): String
  + setName(name: String): void
  + getUserType(): String
  + setUserType(userType: String): void
}

class Student Ellipsis {
}

class Teacher Ellipsis {
}

Student --|> User
Teacher --|> User
@enduml