@startuml
class Student {
  - studentId: String
}

class Course {
  - courseId: String
}

class Enrollment {
  - enrollmentDate: String
  - status: String
  + updateDetails(newDate: String, newStatus: String): void
  + cancel(): void
}

Student "0..*" -- "0..*" Course
(Student, Course) .. Enrollment
@enduml