@startuml
class Book {
    - title: String
    - author: String
    - publicationDate: Date
}

class PageContent {
    - text: String
}

class Document {
    + getMetadata(): Dictionary<String, Object>
    + getPageContent(): PageContent
}

Book "1" --> Document
Document "1" --> PageContent

@enduml