@startuml
class Student {
    + id: ID
    - name: String
}

class Course {
    + id: ID
    - name: String
}

class Enrollment {
    * studentID: ID
    * courseID: ID
}

Student --> Enrollment --|> Course
@enduml