@startuml
class User {
    - username: String
    - password: String
    
    + login(): boolean
}

class Book {
    - title: String
    - author: String
    - publicationYear: Integer
    - description: String
    
    # Methods could be added here if needed
}

User *-- Book
@enduml