@startuml
   class Player {
       - name: String
       - dice1: Die
       - dice2: Die

       + rollDice(): Pair[Integer, Integer]
   }

   class Die {
       - value: Integer

       + roll(): Integer
   }

   Player "1" --> Die: has
   Player:rollDice() -> Pair[Integer, Integer]: result of the dice roll
   @enduml