@startuml
class Document(
    - producer: String,
    - creator: String,
    - creationDate: String,
    - source: String,
    - file_path: String,
    - format: String,
    - title: String,
    - author: String,
    - subject: String,
    - keywords: String[],
    - moddate: String,
    - trapped: Boolean,
    - modDate: String,
    - creationDate: String,
    - page: Integer
)
@enduml