@startuml
class User Ellipsis {
  + registerBook(title: String, author: String, yearOfPublication: int): void
}

class Book Ellipsis {
  - title: String
  - author: String
  - yearOfPublication: int
}

User "1" --> "0..*" Book : registers
@enduml